### ISSUE TITLE
Error on importing NDIlib on PyPy

### ISSUE THREAD

**Issue by avanspector** [buresu/ndi-python#20]
![изображение](https://user-images.githubusercontent.com/94762082/192653334-2467ff55-1682-48ec-b3cb-0d3bb7e550bb.png)

Same issue when installing through PyPy's pip or building yourself.

**Comment by 36agus36** [comment]
I am trying to use it in visual studio and it does not work for me, it is installed but only version 5.1.1.1 and when I try to update it to 5.1.1.5 it gives an error from version 5.1.1.1, and when I import it "import ndi" I get gives error and does not compile. Has this happened to you? Do you know how to fix it?
