### ISSUE TITLE
import NDIlib as ndi errror

### ISSUE THREAD

**Issue by arisprung** [buresu/ndi-python#4]
<img width="581" alt="Screenshot 2020-09-23 143844" src="https://user-images.githubusercontent.com/1506537/94007750-96883d00-fdaa-11ea-8e4f-e6e767adb524.png">
Hi 
I ran both cmake commands and attached 2 files that it generated to the "example" folder but still getting this error. Any idea? See screenshots of my folder structure below
<img width="589" alt="Screenshot 2020-09-23 143420" src="https://user-images.githubusercontent.com/1506537/94007630-66d93500-fdaa-11ea-9193-165aab2bdf18.png">
<img width="590" alt="Screenshot 2020-09-23 143324" src="https://user-images.githubusercontent.com/1506537/94007634-68a2f880-fdaa-11ea-81bc-b98488b06883.png">
<img width="581" alt="Screenshot 2020-09-23 143844" src="https://user-images.githubusercontent.com/1506537/94007750-96883d00-fdaa-11ea-8e4f-e6e767adb524.png">

**Comment by tgentry1986** [comment]
Hi @arisprung how were you able to get cmake to compile this properly on windows? im having a hell of a time here, using cmake-gui. It all appears to work but i dont get a Release directory or NDIlib.lib files etc

**Comment by tgentry1986** [comment]
@arisprung never mind, i figured it out :)

**Comment by evup4s** [comment]
Hi,
I do not succeed in running the cmake commands, and getting the error message;
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:3 (project):
  Running
   'nmake' '-?'
  failed with:
   The system cannot find the file specified
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

Is it possible that the latest NDI-SDK (5.0.11.1) of 19 jan2022 has an issue with the provided "FindNDI.cmake" ????
Thnks in advance for your advice(s) !

**Comment by buresu** [comment]
Hi, sorry for late reply.
ndi-python support pypi repository now.
Please try to install it from pip.
```
pip install ndi-python
```

**Comment by buresu** [comment]
Thank you for your reply. 
This issue will be closed, but if you encounter another problem please create a new issue.
