### ISSUE TITLE
Cant read ndi audio object data 

### ISSUE THREAD

**Issue by tgentry1986** [buresu/ndi-python#7]
Hi There,

I can receive an audio object;

while True:
        # type, video, audio, metadata
        t,v,a,m = ndi.recv_capture_v2(ndi_recv, 5000)

if t == ndi.FRAME_TYPE_AUDIO:
            print("Audio data received (%d channels %d sample rate)." % (a.no_channels, a.sample_rate))
            
 But i cant seem to do anything with it;
 
 print(a.data)
 
 results in;
 
 AttributeError: unreadable attribute
 
 Is this by design/has it not been implemented?
 
 (BTW thanks very much, im loving this project!)

**Comment by tgentry1986** [comment]
hey @buresu - was wondering if you have any thoughts on this? i cant figure it out - and im no c++ developer! Have you been able to receive NDI audio before with this library? am i just doing something wrong?

Thank you so much!

**Comment by buresu** [comment]
Hi, sorry for late reply.
At the time of your question, NDI audio was not yet supported, but it is now supported in the current master 2d194ca5b2470b1cb0e12e27bd8f7f5a81a60a8b.
And I added some examples.

**Comment by tgentry1986** [comment]
Amazing! Thank you!

**Comment by buresu** [comment]
Thank you for your reply.
This issue will be closed, but if you still have problems, please reopen it.
